version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase:4.30.0
    depends_on:
      - postgres
    volumes:
      - ./test_project:/liquibase/changelog
    command:
      - update
      - --changelog-file=changelog.sql
      - --url=jdbc:postgresql://postgres:5432/postgres
      - --username=postgres
      - --password=postgres
    working_dir: /liquibase/changelog